version: '3'

services:
    template_nodejs_express:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: template_nodejs_express
        restart: unless-stopped
        ports:
        - "3050:3000"