version: '3'

services:
    
    template_nodejs_express:
        # entrypoint: ["sh", "-c", "sleep 2073600"] # For debug.
        depends_on:
            - mongo
        image: template-nodejs-express
        container_name: template_nodejs_express
        restart: unless-stopped
        ports:
            - "3000:3000"
            - "9229:9229"
        volumes: 
            - ../:/usr/app
            - /usr/app/node_modules # Prevent host to override container's node_modules.
        networks:
            - global
            
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ../.data:/data/db
        ports:
            - "27017:27017"
        networks:
            - global

networks:
    global: