openapi: '3.0.0'  # https://github.com/cdimascio/express-openapi-validator/blob/master/examples/1-standard/api.yaml
info:
  version: 1.0.0
  title: OpenAPI template-nodejs-express
  description: An API template.
  termsOfService: http://mytermsofservice
  license:
    name: My licence
    url: https://mylicence.url
servers:
  - url: /v1
paths:
  /users:
    post:
      description: Creates a new user.
      operationId: createUser
      security: []        
      requestBody:
        description: User to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: pet response

components:
  schemas:
    User:
      required:
        - userName
      properties:
        userName:
          type: string