openapi: '3.0.0'  # https://github.com/cdimascio/express-openapi-validator/blob/master/examples/1-standard/api.yaml
info:
  version: 1.0.0
  title: OpenAPI template-nodejs-express
  description: An API template.
  termsOfService: http://mytermsofservice
  license:
    name: My licence
    url: https://mylicence.url
servers:
  - url: /v1
paths:
  /users:
    post:
      description: Creates a new user.
      operationId: createUser
      security: []        
      requestBody:
        description: User to create.
        required: true
        content:
          application/json:
            schema:              
              type: object
              required:
                - userName
              properties:
                userName:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                age:
                  type: integer
            examples:
              CreateUserJohnDoe:
                value:
                  userName: jdoe
                  firstName: john
                  lastName: doe
                  age: 30
      responses:
        '201':
          description: pet response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean